### ISSUE TITLE
Auto-Address Cleaner causes failure to send group emails in TB 128.0.X or later

### ISSUE THREAD

**Issue by Prodigalmanboy** [thunderbird-community/Auto-Address-Cleaner#2]
Auto-Address Cleaner causes failure to send group emails in TB 128.0.X or later. It still worked in TB 128.0, but any later version causes TB to fail sending group emails. I use many group emails, and it fails on all of them,

Failure results in the following error message:

_"Your Group Email ... is not a valid email address because it is not of the form user@host. You must correct before sending the email"_

Disabling this add-on fixes the issue. 

Latest release of the add-on (1.3) does not fix the issue.

The issue persists with all other add-ons disabled except for Auto-Address Cleaner. I have not tested this on Linux TB, but it occurs on every Win10 or Win 11 machine I use, both at work and at home.

**Comment by Prodigalmanboy** [comment]
Note: I should have mentioned that whether the group email list has a description or not (I tried both) makes not difference. It does not work either way.

**Comment by jobisoft** [comment]
I changed the detection of lists once more. Does this version work for you? Just drag the link into the add-on manager tab of Thunderbird.

[Auto-Address-Cleaner_1_4.zip](https://github.com/user-attachments/files/16978734/Auto-Address-Cleaner_1_4.zip)

**Comment by Prodigalmanboy** [comment]
Yes, 1.4 works again. Thank you for your work on this. I will fix my review.

I assume there will be a official update?

Thanks again.

**Comment by jobisoft** [comment]
With your positive feedback here, I will release it officially today. It will show up on ATN after it passed review. I keep you posted.

**Comment by jobisoft** [comment]
Released and already reviewed.
