### ISSUE TITLE
not compatible with betterbird?

### ISSUE THREAD

**Issue by 1u** [thunderbird-community/Auto-Address-Cleaner#3]
It shows that only Auto-Address-Cleaner v1.1 is compatible with Betterbird 115.17.0-bb35 (64-Bit)

How come?

Linux, FlatPak.

![image](https://github.com/user-attachments/assets/d20cdc02-c1ed-4860-91e7-0698568b3fc8)

**Comment by jobisoft** [comment]
After the person behind the BB project threatened me with legal consequences just to intimidate me, I realized that the claims against him are not fully taken out of thin air and his Mozilla-wide-participation-ban seems justified. I do not provide support for his project whatsoever. I have no idea what might cause the issue you are seeing, but I will not investigate that further.

**Comment by 1u** [comment]
I comprehend, thank you for sharing.

**Comment by jobisoft** [comment]
I did check what Thunderbird itself is showing and it has the same output. The add-on uses newly added APIs in the most recent version, which are not yet available in Thunderbird 115. What you see is therefore correct.
